/* Generated by Cython 0.10 on Sun Nov  9 17:13:33 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__protoplex___speedups


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static void __Pyx_RaiseArgtupleInvalid(const char* func_name, int exact,
    Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/

static INLINE int __Pyx_CheckKeywordStrings(PyObject *kwdict,
    const char* function_name, int kw_allowed); /*proto*/

static INLINE PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i, int is_unsigned) {
    PyObject *r;
    if (PyList_CheckExact(o) && 0 <= i && i < PyList_GET_SIZE(o)) {
        r = PyList_GET_ITEM(o, i);
        Py_INCREF(r);
    }
    else if (PyTuple_CheckExact(o) && 0 <= i && i < PyTuple_GET_SIZE(o)) {
        r = PyTuple_GET_ITEM(o, i);
        Py_INCREF(r);
    }
    else if (Py_TYPE(o)->tp_as_sequence && Py_TYPE(o)->tp_as_sequence->sq_item && (likely(i >= 0) || !is_unsigned))
        r = PySequence_GetItem(o, i);
    else {
        PyObject *j = (likely(i >= 0) || !is_unsigned) ? PyInt_FromLong(i) : PyLong_FromUnsignedLongLong((sizeof(unsigned long long) > sizeof(Py_ssize_t) ? (1ULL << (sizeof(Py_ssize_t)*8)) : 0) + i);
        if (!j)
            return 0;
        r = PyObject_GetItem(o, j);
        Py_DECREF(j);
    }
    return r;
}

static INLINE int __Pyx_SetItemInt(PyObject *o, Py_ssize_t i, PyObject *v, int is_unsigned) {
    int r;
    if (PyList_CheckExact(o) && 0 <= i && i < PyList_GET_SIZE(o)) {
        Py_DECREF(PyList_GET_ITEM(o, i));
        Py_INCREF(v);
        PyList_SET_ITEM(o, i, v);
        return 1;
    }
    else if (Py_TYPE(o)->tp_as_sequence && Py_TYPE(o)->tp_as_sequence->sq_ass_item && (likely(i >= 0) || !is_unsigned))
        r = PySequence_SetItem(o, i, v);
    else {
        PyObject *j = (likely(i >= 0) || !is_unsigned) ? PyInt_FromLong(i) : PyLong_FromUnsignedLongLong((sizeof(unsigned long long) > sizeof(Py_ssize_t) ? (1ULL << (sizeof(Py_ssize_t)*8)) : 0) + i);
        if (!j)
            return -1;
        r = PyObject_SetItem(o, j, v);
        Py_DECREF(j);
    }
    return r;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static PyObject *__Pyx_UnpackItem(PyObject *, Py_ssize_t index); /*proto*/
static int __Pyx_EndUnpack(PyObject *); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */

/* "/Users/tav/work/trunk/protoplex/_speedups.pyx":34
 * last_id = 1 # long
 * 
 * cdef class Namespace:             # <<<<<<<<<<<<<<
 *     """A Namespace object."""
 * 
 */

struct __pyx_obj_9protoplex_9_speedups_Namespace {
  PyObject_HEAD
  PyObject *__weakref__;
  PyObject *env;
  int id;
};
/* Module declarations from protoplex._speedups */

static PyTypeObject *__pyx_ptype_9protoplex_9_speedups_Namespace = 0;
static PyObject *__pyx_v_9protoplex_9_speedups_store = 0;
static PyObject *__pyx_v_9protoplex_9_speedups_inverted_store = 0;
static int __pyx_v_9protoplex_9_speedups_last_id;
static int __pyx_f_9protoplex_9_speedups_typecheck(PyObject *, PyObject *); /*proto*/
static PyObject *__pyx_f_9protoplex_9_speedups__prune_stores(void); /*proto*/


/* Implementation of protoplex._speedups */
static PyObject *__pyx_int_0;
static char __pyx_k___cinit__[] = "__cinit__";
static PyObject *__pyx_kp___cinit__;
static char __pyx_k___getattribute__[] = "__getattribute__";
static PyObject *__pyx_kp___getattribute__;
static char __pyx_k___str__[] = "__str__";
static PyObject *__pyx_kp___str__;
static char __pyx_k___repr__[] = "__repr__";
static PyObject *__pyx_kp___repr__;
static char __pyx_k___dir__[] = "__dir__";
static PyObject *__pyx_kp___dir__;
static char __pyx_k_attribute[] = "attribute";
static PyObject *__pyx_kp_attribute;
static char __pyx_k_sys[] = "sys";
static PyObject *__pyx_kp_sys;
static char __pyx_k__getframe[] = "_getframe";
static PyObject *__pyx_kp__getframe;
static char __pyx_k_get_frame[] = "get_frame";
static PyObject *__pyx_kp_get_frame;
static char __pyx_k_f_locals[] = "f_locals";
static PyObject *__pyx_kp_f_locals;
static char __pyx_k_startswith[] = "startswith";
static PyObject *__pyx_kp_startswith;
static char __pyx_k_1[] = "_";
static PyObject *__pyx_kp_1;
static char __pyx_k_2[] = "__";
static PyObject *__pyx_kp_2;
static char __pyx_k_AttributeError[] = "AttributeError";
static PyObject *__pyx_kp_AttributeError;
static char __pyx_k_4[] = "__str__";
static PyObject *__pyx_kp_4;
static char __pyx_k_5[] = "__repr__";
static PyObject *__pyx_kp_5;
static PyObject *__pyx_builtin_AttributeError;
static PyObject *__pyx_kp_3;
static char __pyx_k_3[] = "'Namespace' object has no attribute %r";

/* "/Users/tav/work/trunk/protoplex/_speedups.pyx":24
 *     int PyUnicode_Tailmatch(object str, object substr, Py_ssize_t start, Py_ssize_t end, int direction)
 * 
 * cdef inline bint typecheck(object ob, object tp):             # <<<<<<<<<<<<<<
 *     return PyObject_TypeCheck(ob, <PyTypeObject*>tp)
 * 
 */

static INLINE int __pyx_f_9protoplex_9_speedups_typecheck(PyObject *__pyx_v_ob, PyObject *__pyx_v_tp) {
  int __pyx_r;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":25
 * 
 * cdef inline bint typecheck(object ob, object tp):
 *     return PyObject_TypeCheck(ob, <PyTypeObject*>tp)             # <<<<<<<<<<<<<<
 * 
 * cdef dict store, inverted_store
 */
  __pyx_r = PyObject_TypeCheck(__pyx_v_ob, ((PyTypeObject *)__pyx_v_tp));
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/tav/work/trunk/protoplex/_speedups.pyx":41
 *     cdef int id
 * 
 *     def __cinit__(Namespace self, **env):             # <<<<<<<<<<<<<<
 * 
 *         cdef object key, obj
 */

static int __pyx_pf_9protoplex_9_speedups_9Namespace___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_9protoplex_9_speedups_9Namespace___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_env = 0;
  PyObject *__pyx_v_key;
  PyObject *__pyx_v__keys;
  PyObject *__pyx_v_keys;
  PyObject *__pyx_v_id_data;
  int __pyx_v_id;
  PyObject *__pyx_v_name;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_ssize_t __pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  int __pyx_8;
  int __pyx_9;
  PyObject *__pyx_10;
  if (unlikely(PyTuple_GET_SIZE(__pyx_args) > 0)) {
    __Pyx_RaiseArgtupleInvalid("__cinit__", 1, 0, 0, PyTuple_GET_SIZE(__pyx_args)); return -1;}
  if (__pyx_kwds && unlikely(!__Pyx_CheckKeywordStrings(__pyx_kwds, "__cinit__", 1))) return -1;
  __pyx_v_env = (__pyx_kwds) ? PyDict_Copy(__pyx_kwds) : PyDict_New();
  if (unlikely(!__pyx_v_env)) return -1;
  __pyx_v_key = Py_None; Py_INCREF(Py_None);
  __pyx_v__keys = ((PyObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_keys = ((PyObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_id_data = ((PyObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_name = Py_None; Py_INCREF(Py_None);

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":50
 *         cdef int id
 * 
 *         if env:             # <<<<<<<<<<<<<<
 *             _keys = PyDict_Keys(env)
 *         else:
 */
  __pyx_1 = __Pyx_PyObject_IsTrue(__pyx_v_env); if (unlikely(__pyx_1 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__pyx_1) {

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":51
 * 
 *         if env:
 *             _keys = PyDict_Keys(env)             # <<<<<<<<<<<<<<
 *         else:
 *             env = get_frame(0).f_locals
 */
    __pyx_2 = PyDict_Keys(__pyx_v_env); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (!(likely(PyList_CheckExact(__pyx_2)) || (__pyx_2) == Py_None || (PyErr_Format(PyExc_TypeError, "Expected list, got %s", Py_TYPE(__pyx_2)->tp_name), 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(((PyObject *)__pyx_v__keys));
    __pyx_v__keys = ((PyObject *)__pyx_2);
    __pyx_2 = 0;
    goto __pyx_L5;
  }
  /*else*/ {

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":53
 *             _keys = PyDict_Keys(env)
 *         else:
 *             env = get_frame(0).f_locals             # <<<<<<<<<<<<<<
 *             _keys = [
 *                 name for name in PyDict_Keys(env)
 */
    __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_get_frame); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_INCREF(__pyx_int_0);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_int_0);
    __pyx_4 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
    __pyx_2 = PyObject_GetAttr(__pyx_4, __pyx_kp_f_locals); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_v_env);
    __pyx_v_env = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":54
 *         else:
 *             env = get_frame(0).f_locals
 *             _keys = [             # <<<<<<<<<<<<<<
 *                 name for name in PyDict_Keys(env)
 *                 if not (name.startswith('_') and (not name.startswith('__')))
 */
    __pyx_3 = PyList_New(0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":55
 *             env = get_frame(0).f_locals
 *             _keys = [
 *                 name for name in PyDict_Keys(env)             # <<<<<<<<<<<<<<
 *                 if not (name.startswith('_') and (not name.startswith('__')))
 *                 ]
 */
    __pyx_4 = PyDict_Keys(__pyx_v_env); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (PyList_CheckExact(__pyx_4) || PyTuple_CheckExact(__pyx_4)) {
      __pyx_5 = 0; __pyx_2 = __pyx_4; Py_INCREF(__pyx_2);
    } else {
      __pyx_5 = -1; __pyx_2 = PyObject_GetIter(__pyx_4); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    }
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    for (;;) {
      if (likely(PyList_CheckExact(__pyx_2))) {
        if (__pyx_5 >= PyList_GET_SIZE(__pyx_2)) break;
        __pyx_4 = PyList_GET_ITEM(__pyx_2, __pyx_5); Py_INCREF(__pyx_4); __pyx_5++;
      } else if (likely(PyTuple_CheckExact(__pyx_2))) {
        if (__pyx_5 >= PyTuple_GET_SIZE(__pyx_2)) break;
        __pyx_4 = PyTuple_GET_ITEM(__pyx_2, __pyx_5); Py_INCREF(__pyx_4); __pyx_5++;
      } else {
        __pyx_4 = PyIter_Next(__pyx_2);
        if (!__pyx_4) {
          if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
          break;
        }
      }
      Py_DECREF(__pyx_v_name);
      __pyx_v_name = __pyx_4;
      __pyx_4 = 0;

      /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":56
 *             _keys = [
 *                 name for name in PyDict_Keys(env)
 *                 if not (name.startswith('_') and (not name.startswith('__')))             # <<<<<<<<<<<<<<
 *                 ]
 * 
 */
      __pyx_4 = PyObject_GetAttr(__pyx_v_name, __pyx_kp_startswith); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __pyx_6 = PyTuple_New(1); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_INCREF(__pyx_kp_1);
      PyTuple_SET_ITEM(__pyx_6, 0, __pyx_kp_1);
      __pyx_7 = PyObject_Call(__pyx_4, ((PyObject *)__pyx_6), NULL); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(((PyObject *)__pyx_6)); __pyx_6 = 0;
      __pyx_1 = __Pyx_PyObject_IsTrue(__pyx_7); if (unlikely(__pyx_1 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_DECREF(__pyx_7); __pyx_7 = 0;
      if (__pyx_1) {
        __pyx_4 = PyObject_GetAttr(__pyx_v_name, __pyx_kp_startswith); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        __pyx_6 = PyTuple_New(1); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_INCREF(__pyx_kp_2);
        PyTuple_SET_ITEM(__pyx_6, 0, __pyx_kp_2);
        __pyx_7 = PyObject_Call(__pyx_4, ((PyObject *)__pyx_6), NULL); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_DECREF(__pyx_4); __pyx_4 = 0;
        Py_DECREF(((PyObject *)__pyx_6)); __pyx_6 = 0;
        __pyx_8 = __Pyx_PyObject_IsTrue(__pyx_7); if (unlikely(__pyx_8 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_DECREF(__pyx_7); __pyx_7 = 0;
        __pyx_1 = (!__pyx_8);
      }
      __pyx_8 = (!__pyx_1);
      if (__pyx_8) {

        /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":55
 *             env = get_frame(0).f_locals
 *             _keys = [
 *                 name for name in PyDict_Keys(env)             # <<<<<<<<<<<<<<
 *                 if not (name.startswith('_') and (not name.startswith('__')))
 *                 ]
 */
        __pyx_9 = PyList_Append(__pyx_3, (PyObject*)__pyx_v_name); if (unlikely(__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        goto __pyx_L8;
      }
      __pyx_L8:;
    }
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(((PyObject *)__pyx_v__keys));
    __pyx_v__keys = __pyx_3;
    __pyx_3 = 0;
  }
  __pyx_L5:;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":59
 *                 ]
 * 
 *         PyList_Sort(_keys)             # <<<<<<<<<<<<<<
 *         keys = PyList_AsTuple(_keys)
 * 
 */
  PyList_Sort(((PyObject *)__pyx_v__keys));

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":60
 * 
 *         PyList_Sort(_keys)
 *         keys = PyList_AsTuple(_keys)             # <<<<<<<<<<<<<<
 * 
 *         if PyDict_Contains(inverted_store, keys):
 */
  __pyx_4 = PyList_AsTuple(((PyObject *)__pyx_v__keys)); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (!(likely(PyTuple_CheckExact(__pyx_4)) || (__pyx_4) == Py_None || (PyErr_Format(PyExc_TypeError, "Expected tuple, got %s", Py_TYPE(__pyx_4)->tp_name), 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_v_keys));
  __pyx_v_keys = ((PyObject *)__pyx_4);
  __pyx_4 = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":62
 *         keys = PyList_AsTuple(_keys)
 * 
 *         if PyDict_Contains(inverted_store, keys):             # <<<<<<<<<<<<<<
 *             id_data = <object>PyDict_GetItem(inverted_store, keys)
 *             id = id_data[0]
 */
  __pyx_9 = PyDict_Contains(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store), ((PyObject *)__pyx_v_keys));
  if (__pyx_9) {

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":63
 * 
 *         if PyDict_Contains(inverted_store, keys):
 *             id_data = <object>PyDict_GetItem(inverted_store, keys)             # <<<<<<<<<<<<<<
 *             id = id_data[0]
 *             PyList_Append(id_data, PyWeakref_NewRef(self, None))
 */
    __pyx_10 = PyDict_GetItem(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store), ((PyObject *)__pyx_v_keys));
    if (!(likely(PyList_CheckExact(((PyObject *)__pyx_10))) || (((PyObject *)__pyx_10)) == Py_None || (PyErr_Format(PyExc_TypeError, "Expected list, got %s", Py_TYPE(((PyObject *)__pyx_10))->tp_name), 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_INCREF(((PyObject *)__pyx_10));
    Py_DECREF(((PyObject *)__pyx_v_id_data));
    __pyx_v_id_data = ((PyObject *)((PyObject *)__pyx_10));

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":64
 *         if PyDict_Contains(inverted_store, keys):
 *             id_data = <object>PyDict_GetItem(inverted_store, keys)
 *             id = id_data[0]             # <<<<<<<<<<<<<<
 *             PyList_Append(id_data, PyWeakref_NewRef(self, None))
 *         else:
 */
    __pyx_6 = __Pyx_GetItemInt(((PyObject *)__pyx_v_id_data), 0, 0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_9 = __pyx_PyInt_int(__pyx_6); if (unlikely((__pyx_9 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_v_id = __pyx_9;

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":65
 *             id_data = <object>PyDict_GetItem(inverted_store, keys)
 *             id = id_data[0]
 *             PyList_Append(id_data, PyWeakref_NewRef(self, None))             # <<<<<<<<<<<<<<
 *         else:
 *             global last_id
 */
    __pyx_7 = PyWeakref_NewRef(__pyx_v_self, Py_None); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    PyList_Append(((PyObject *)__pyx_v_id_data), __pyx_7);
    Py_DECREF(__pyx_7); __pyx_7 = 0;
    goto __pyx_L9;
  }
  /*else*/ {

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":68
 *         else:
 *             global last_id
 *             id = last_id             # <<<<<<<<<<<<<<
 *             last_id = id + 1
 *             inverted_store[keys] = [id, PyWeakref_NewRef(self, None)]
 */
    __pyx_v_id = __pyx_v_9protoplex_9_speedups_last_id;

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":69
 *             global last_id
 *             id = last_id
 *             last_id = id + 1             # <<<<<<<<<<<<<<
 *             inverted_store[keys] = [id, PyWeakref_NewRef(self, None)]
 *             store[id] = keys
 */
    __pyx_v_9protoplex_9_speedups_last_id = (__pyx_v_id + 1);

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":70
 *             id = last_id
 *             last_id = id + 1
 *             inverted_store[keys] = [id, PyWeakref_NewRef(self, None)]             # <<<<<<<<<<<<<<
 *             store[id] = keys
 * 
 */
    __pyx_2 = PyInt_FromLong(__pyx_v_id); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_3 = PyWeakref_NewRef(__pyx_v_self, Py_None); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_4 = PyList_New(2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    PyList_SET_ITEM(__pyx_4, 0, __pyx_2);
    PyList_SET_ITEM(__pyx_4, 1, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    if (PyObject_SetItem(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store), ((PyObject *)__pyx_v_keys), ((PyObject *)__pyx_4)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":71
 *             last_id = id + 1
 *             inverted_store[keys] = [id, PyWeakref_NewRef(self, None)]
 *             store[id] = keys             # <<<<<<<<<<<<<<
 * 
 *         self.id = id
 */
    if (__Pyx_SetItemInt(((PyObject *)__pyx_v_9protoplex_9_speedups_store), __pyx_v_id, ((PyObject *)__pyx_v_keys), 0) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  __pyx_L9:;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":73
 *             store[id] = keys
 * 
 *         self.id = id             # <<<<<<<<<<<<<<
 *         self.env = [env[key] for key in keys]
 * 
 */
  ((struct __pyx_obj_9protoplex_9_speedups_Namespace *)__pyx_v_self)->id = __pyx_v_id;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":74
 * 
 *         self.id = id
 *         self.env = [env[key] for key in keys]             # <<<<<<<<<<<<<<
 * 
 *     def __getattribute__(Namespace self, attribute):
 */
  __pyx_6 = PyList_New(0); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyList_CheckExact(((PyObject *)__pyx_v_keys)) || PyTuple_CheckExact(((PyObject *)__pyx_v_keys))) {
    __pyx_5 = 0; __pyx_7 = ((PyObject *)__pyx_v_keys); Py_INCREF(__pyx_7);
  } else {
    __pyx_5 = -1; __pyx_7 = PyObject_GetIter(((PyObject *)__pyx_v_keys)); if (unlikely(!__pyx_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  for (;;) {
    if (likely(PyList_CheckExact(__pyx_7))) {
      if (__pyx_5 >= PyList_GET_SIZE(__pyx_7)) break;
      __pyx_2 = PyList_GET_ITEM(__pyx_7, __pyx_5); Py_INCREF(__pyx_2); __pyx_5++;
    } else if (likely(PyTuple_CheckExact(__pyx_7))) {
      if (__pyx_5 >= PyTuple_GET_SIZE(__pyx_7)) break;
      __pyx_2 = PyTuple_GET_ITEM(__pyx_7, __pyx_5); Py_INCREF(__pyx_2); __pyx_5++;
    } else {
      __pyx_2 = PyIter_Next(__pyx_7);
      if (!__pyx_2) {
        if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        break;
      }
    }
    Py_DECREF(__pyx_v_key);
    __pyx_v_key = __pyx_2;
    __pyx_2 = 0;
    __pyx_3 = PyObject_GetItem(__pyx_v_env, __pyx_v_key); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_9 = PyList_Append(__pyx_6, (PyObject*)__pyx_3); if (unlikely(__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }
  Py_DECREF(__pyx_7); __pyx_7 = 0;
  Py_DECREF(((PyObject *)((struct __pyx_obj_9protoplex_9_speedups_Namespace *)__pyx_v_self)->env));
  ((struct __pyx_obj_9protoplex_9_speedups_Namespace *)__pyx_v_self)->env = __pyx_6;
  __pyx_6 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  __Pyx_AddTraceback("protoplex._speedups.Namespace.__cinit__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_env);
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v__keys);
  Py_DECREF(__pyx_v_keys);
  Py_DECREF(__pyx_v_id_data);
  Py_DECREF(__pyx_v_name);
  return __pyx_r;
}

/* "/Users/tav/work/trunk/protoplex/_speedups.pyx":76
 *         self.env = [env[key] for key in keys]
 * 
 *     def __getattribute__(Namespace self, attribute):             # <<<<<<<<<<<<<<
 *         cdef int i
 *         cdef object key
 */

static PyObject *__pyx_pf_9protoplex_9_speedups_9Namespace___getattribute__(PyObject *__pyx_v_self, PyObject *__pyx_v_attribute); /*proto*/
static PyObject *__pyx_pf_9protoplex_9_speedups_9Namespace___getattribute__(PyObject *__pyx_v_self, PyObject *__pyx_v_attribute) {
  int __pyx_v_i;
  PyObject *__pyx_v_key;
  PyObject *__pyx_r;
  Py_ssize_t __pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  PyObject *__pyx_t_1 = NULL;
  __pyx_v_key = Py_None; Py_INCREF(Py_None);

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":79
 *         cdef int i
 *         cdef object key
 *         i = 0             # <<<<<<<<<<<<<<
 *         for key in store[self.id]:
 *             if key == attribute:
 */
  __pyx_v_i = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":80
 *         cdef object key
 *         i = 0
 *         for key in store[self.id]:             # <<<<<<<<<<<<<<
 *             if key == attribute:
 *                 return self.env[i]
 */
  __pyx_2 = __Pyx_GetItemInt(((PyObject *)__pyx_v_9protoplex_9_speedups_store), ((struct __pyx_obj_9protoplex_9_speedups_Namespace *)__pyx_v_self)->id, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyList_CheckExact(__pyx_2) || PyTuple_CheckExact(__pyx_2)) {
    __pyx_1 = 0; __pyx_3 = __pyx_2; Py_INCREF(__pyx_3);
  } else {
    __pyx_1 = -1; __pyx_3 = PyObject_GetIter(__pyx_2); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  for (;;) {
    if (likely(PyList_CheckExact(__pyx_3))) {
      if (__pyx_1 >= PyList_GET_SIZE(__pyx_3)) break;
      __pyx_2 = PyList_GET_ITEM(__pyx_3, __pyx_1); Py_INCREF(__pyx_2); __pyx_1++;
    } else if (likely(PyTuple_CheckExact(__pyx_3))) {
      if (__pyx_1 >= PyTuple_GET_SIZE(__pyx_3)) break;
      __pyx_2 = PyTuple_GET_ITEM(__pyx_3, __pyx_1); Py_INCREF(__pyx_2); __pyx_1++;
    } else {
      __pyx_2 = PyIter_Next(__pyx_3);
      if (!__pyx_2) {
        if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        break;
      }
    }
    Py_DECREF(__pyx_v_key);
    __pyx_v_key = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":81
 *         i = 0
 *         for key in store[self.id]:
 *             if key == attribute:             # <<<<<<<<<<<<<<
 *                 return self.env[i]
 *             i = i + 1
 */
    __pyx_2 = PyObject_RichCompare(__pyx_v_key, __pyx_v_attribute, Py_EQ); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_4 = __Pyx_PyObject_IsTrue(__pyx_2); if (unlikely(__pyx_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__pyx_4) {

      /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":82
 *         for key in store[self.id]:
 *             if key == attribute:
 *                 return self.env[i]             # <<<<<<<<<<<<<<
 *             i = i + 1
 *         raise AttributeError("'Namespace' object has no attribute %r" % attribute)
 */
      __pyx_2 = __Pyx_GetItemInt(((PyObject *)((struct __pyx_obj_9protoplex_9_speedups_Namespace *)__pyx_v_self)->env), __pyx_v_i, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __pyx_r = __pyx_2;
      __pyx_2 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      goto __pyx_L0;
      goto __pyx_L7;
    }
    __pyx_L7:;

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":83
 *             if key == attribute:
 *                 return self.env[i]
 *             i = i + 1             # <<<<<<<<<<<<<<
 *         raise AttributeError("'Namespace' object has no attribute %r" % attribute)
 * 
 */
    __pyx_v_i = (__pyx_v_i + 1);
  }
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":84
 *                 return self.env[i]
 *             i = i + 1
 *         raise AttributeError("'Namespace' object has no attribute %r" % attribute)             # <<<<<<<<<<<<<<
 * 
 *     def __str__(Namespace self):
 */
  __pyx_t_1 = PyNumber_Remainder(__pyx_kp_3, __pyx_v_attribute); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_t_1);
  __pyx_t_1 = 0;
  __pyx_3 = PyObject_Call(__pyx_builtin_AttributeError, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __Pyx_Raise(__pyx_3, 0, 0);
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("protoplex._speedups.Namespace.__getattribute__");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_key);
  return __pyx_r;
}

/* "/Users/tav/work/trunk/protoplex/_speedups.pyx":86
 *         raise AttributeError("'Namespace' object has no attribute %r" % attribute)
 * 
 *     def __str__(Namespace self):             # <<<<<<<<<<<<<<
 *         return getattr(self, ('__str__'))()
 * 
 */

static PyObject *__pyx_pf_9protoplex_9_speedups_9Namespace___str__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_pf_9protoplex_9_speedups_9Namespace___str__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":87
 * 
 *     def __str__(Namespace self):
 *         return getattr(self, ('__str__'))()             # <<<<<<<<<<<<<<
 * 
 *     def __repr__(Namespace self):
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_kp_4); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("protoplex._speedups.Namespace.__str__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/tav/work/trunk/protoplex/_speedups.pyx":89
 *         return getattr(self, ('__str__'))()
 * 
 *     def __repr__(Namespace self):             # <<<<<<<<<<<<<<
 *         return getattr(self, ('__repr__'))()
 * 
 */

static PyObject *__pyx_pf_9protoplex_9_speedups_9Namespace___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_pf_9protoplex_9_speedups_9Namespace___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":90
 * 
 *     def __repr__(Namespace self):
 *         return getattr(self, ('__repr__'))()             # <<<<<<<<<<<<<<
 * 
 *     def __dir__(Namespace self):
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_kp_5); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("protoplex._speedups.Namespace.__repr__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/tav/work/trunk/protoplex/_speedups.pyx":92
 *         return getattr(self, ('__repr__'))()
 * 
 *     def __dir__(Namespace self):             # <<<<<<<<<<<<<<
 *         return list(store[self.id])
 * 
 */

static PyObject *__pyx_pf_9protoplex_9_speedups_9Namespace___dir__(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_9protoplex_9_speedups_9Namespace___dir__(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":93
 * 
 *     def __dir__(Namespace self):
 *         return list(store[self.id])             # <<<<<<<<<<<<<<
 * 
 * cdef _prune_stores():
 */
  __pyx_1 = __Pyx_GetItemInt(((PyObject *)__pyx_v_9protoplex_9_speedups_store), ((struct __pyx_obj_9protoplex_9_speedups_Namespace *)__pyx_v_self)->id, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_Call(((PyObject *)((PyObject*)&PyList_Type)), ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("protoplex._speedups.Namespace.__dir__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/tav/work/trunk/protoplex/_speedups.pyx":95
 *         return list(store[self.id])
 * 
 * cdef _prune_stores():             # <<<<<<<<<<<<<<
 *     cdef list remlist, surv
 *     cdef int id
 */

static  PyObject *__pyx_f_9protoplex_9_speedups__prune_stores(void) {
  PyObject *__pyx_v_remlist;
  PyObject *__pyx_v_surv;
  int __pyx_v_id;
  PyObject *__pyx_v_key;
  PyObject *__pyx_v_val;
  PyObject *__pyx_v_item;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_ssize_t __pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4;
  Py_ssize_t __pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  int __pyx_7;
  int __pyx_8;
  PyObject *__pyx_9 = 0;
  __pyx_v_remlist = ((PyObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_surv = ((PyObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_key = Py_None; Py_INCREF(Py_None);
  __pyx_v_val = Py_None; Py_INCREF(Py_None);
  __pyx_v_item = Py_None; Py_INCREF(Py_None);

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":98
 *     cdef list remlist, surv
 *     cdef int id
 *     remlist = []             # <<<<<<<<<<<<<<
 *     for key in inverted_store:
 *         val = <object>PyDict_GetItem(inverted_store, key)
 */
  __pyx_1 = PyList_New(0); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_v_remlist));
  __pyx_v_remlist = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":99
 *     cdef int id
 *     remlist = []
 *     for key in inverted_store:             # <<<<<<<<<<<<<<
 *         val = <object>PyDict_GetItem(inverted_store, key)
 *         surv = []
 */
  if (PyList_CheckExact(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store)) || PyTuple_CheckExact(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store))) {
    __pyx_2 = 0; __pyx_1 = ((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store); Py_INCREF(__pyx_1);
  } else {
    __pyx_2 = -1; __pyx_1 = PyObject_GetIter(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  }
  for (;;) {
    if (likely(PyList_CheckExact(__pyx_1))) {
      if (__pyx_2 >= PyList_GET_SIZE(__pyx_1)) break;
      __pyx_3 = PyList_GET_ITEM(__pyx_1, __pyx_2); Py_INCREF(__pyx_3); __pyx_2++;
    } else if (likely(PyTuple_CheckExact(__pyx_1))) {
      if (__pyx_2 >= PyTuple_GET_SIZE(__pyx_1)) break;
      __pyx_3 = PyTuple_GET_ITEM(__pyx_1, __pyx_2); Py_INCREF(__pyx_3); __pyx_2++;
    } else {
      __pyx_3 = PyIter_Next(__pyx_1);
      if (!__pyx_3) {
        if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        break;
      }
    }
    Py_DECREF(__pyx_v_key);
    __pyx_v_key = __pyx_3;
    __pyx_3 = 0;

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":100
 *     remlist = []
 *     for key in inverted_store:
 *         val = <object>PyDict_GetItem(inverted_store, key)             # <<<<<<<<<<<<<<
 *         surv = []
 *         id = 0
 */
    __pyx_4 = PyDict_GetItem(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store), __pyx_v_key);
    Py_INCREF(((PyObject *)__pyx_4));
    Py_DECREF(__pyx_v_val);
    __pyx_v_val = ((PyObject *)__pyx_4);

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":101
 *     for key in inverted_store:
 *         val = <object>PyDict_GetItem(inverted_store, key)
 *         surv = []             # <<<<<<<<<<<<<<
 *         id = 0
 *         for item in val:
 */
    __pyx_3 = PyList_New(0); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    Py_DECREF(((PyObject *)__pyx_v_surv));
    __pyx_v_surv = __pyx_3;
    __pyx_3 = 0;

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":102
 *         val = <object>PyDict_GetItem(inverted_store, key)
 *         surv = []
 *         id = 0             # <<<<<<<<<<<<<<
 *         for item in val:
 *             if id == 0:
 */
    __pyx_v_id = 0;

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":103
 *         surv = []
 *         id = 0
 *         for item in val:             # <<<<<<<<<<<<<<
 *             if id == 0:
 *                 id = item
 */
    if (PyList_CheckExact(__pyx_v_val) || PyTuple_CheckExact(__pyx_v_val)) {
      __pyx_5 = 0; __pyx_3 = __pyx_v_val; Py_INCREF(__pyx_3);
    } else {
      __pyx_5 = -1; __pyx_3 = PyObject_GetIter(__pyx_v_val); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    }
    for (;;) {
      if (likely(PyList_CheckExact(__pyx_3))) {
        if (__pyx_5 >= PyList_GET_SIZE(__pyx_3)) break;
        __pyx_6 = PyList_GET_ITEM(__pyx_3, __pyx_5); Py_INCREF(__pyx_6); __pyx_5++;
      } else if (likely(PyTuple_CheckExact(__pyx_3))) {
        if (__pyx_5 >= PyTuple_GET_SIZE(__pyx_3)) break;
        __pyx_6 = PyTuple_GET_ITEM(__pyx_3, __pyx_5); Py_INCREF(__pyx_6); __pyx_5++;
      } else {
        __pyx_6 = PyIter_Next(__pyx_3);
        if (!__pyx_6) {
          if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
          break;
        }
      }
      Py_DECREF(__pyx_v_item);
      __pyx_v_item = __pyx_6;
      __pyx_6 = 0;

      /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":104
 *         id = 0
 *         for item in val:
 *             if id == 0:             # <<<<<<<<<<<<<<
 *                 id = item
 *             else:
 */
      __pyx_7 = (__pyx_v_id == 0);
      if (__pyx_7) {

        /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":105
 *         for item in val:
 *             if id == 0:
 *                 id = item             # <<<<<<<<<<<<<<
 *             else:
 *                 if item():
 */
        __pyx_8 = __pyx_PyInt_int(__pyx_v_item); if (unlikely((__pyx_8 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        __pyx_v_id = __pyx_8;
        goto __pyx_L7;
      }
      /*else*/ {

        /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":107
 *                 id = item
 *             else:
 *                 if item():             # <<<<<<<<<<<<<<
 *                     PyList_Append(surv, item)
 *         if surv:
 */
        __pyx_6 = PyObject_Call(__pyx_v_item, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        __pyx_7 = __Pyx_PyObject_IsTrue(__pyx_6); if (unlikely(__pyx_7 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        if (__pyx_7) {

          /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":108
 *             else:
 *                 if item():
 *                     PyList_Append(surv, item)             # <<<<<<<<<<<<<<
 *         if surv:
 *             PyList_Insert(surv, 0, id)
 */
          PyList_Append(((PyObject *)__pyx_v_surv), __pyx_v_item);
          goto __pyx_L8;
        }
        __pyx_L8:;
      }
      __pyx_L7:;
    }
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":109
 *                 if item():
 *                     PyList_Append(surv, item)
 *         if surv:             # <<<<<<<<<<<<<<
 *             PyList_Insert(surv, 0, id)
 *             PyDict_SetItem(inverted_store, key, surv)
 */
    __pyx_7 = __Pyx_PyObject_IsTrue(((PyObject *)__pyx_v_surv)); if (unlikely(__pyx_7 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    if (__pyx_7) {

      /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":110
 *                     PyList_Append(surv, item)
 *         if surv:
 *             PyList_Insert(surv, 0, id)             # <<<<<<<<<<<<<<
 *             PyDict_SetItem(inverted_store, key, surv)
 *         else:
 */
      __pyx_6 = PyInt_FromLong(__pyx_v_id); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      PyList_Insert(((PyObject *)__pyx_v_surv), 0, __pyx_6);
      Py_DECREF(__pyx_6); __pyx_6 = 0;

      /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":111
 *         if surv:
 *             PyList_Insert(surv, 0, id)
 *             PyDict_SetItem(inverted_store, key, surv)             # <<<<<<<<<<<<<<
 *         else:
 *             PyList_Append(remlist, (key, id))
 */
      PyDict_SetItem(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store), __pyx_v_key, ((PyObject *)__pyx_v_surv));
      goto __pyx_L9;
    }
    /*else*/ {

      /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":113
 *             PyDict_SetItem(inverted_store, key, surv)
 *         else:
 *             PyList_Append(remlist, (key, id))             # <<<<<<<<<<<<<<
 *     if remlist:
 *         for key, id in remlist:
 */
      __pyx_3 = PyInt_FromLong(__pyx_v_id); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __pyx_6 = PyTuple_New(2); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      Py_INCREF(__pyx_v_key);
      PyTuple_SET_ITEM(__pyx_6, 0, __pyx_v_key);
      PyTuple_SET_ITEM(__pyx_6, 1, __pyx_3);
      __pyx_3 = 0;
      PyList_Append(((PyObject *)__pyx_v_remlist), ((PyObject *)__pyx_6));
      Py_DECREF(((PyObject *)__pyx_6)); __pyx_6 = 0;
    }
    __pyx_L9:;
  }
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":114
 *         else:
 *             PyList_Append(remlist, (key, id))
 *     if remlist:             # <<<<<<<<<<<<<<
 *         for key, id in remlist:
 *             PyDict_DelItem(inverted_store, key)
 */
  __pyx_7 = __Pyx_PyObject_IsTrue(((PyObject *)__pyx_v_remlist)); if (unlikely(__pyx_7 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__pyx_7) {

    /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":115
 *             PyList_Append(remlist, (key, id))
 *     if remlist:
 *         for key, id in remlist:             # <<<<<<<<<<<<<<
 *             PyDict_DelItem(inverted_store, key)
 *             PyDict_DelItem(store, id)
 */
    if (PyList_CheckExact(((PyObject *)__pyx_v_remlist)) || PyTuple_CheckExact(((PyObject *)__pyx_v_remlist))) {
      __pyx_5 = 0; __pyx_3 = ((PyObject *)__pyx_v_remlist); Py_INCREF(__pyx_3);
    } else {
      __pyx_5 = -1; __pyx_3 = PyObject_GetIter(((PyObject *)__pyx_v_remlist)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    }
    for (;;) {
      if (likely(PyList_CheckExact(__pyx_3))) {
        if (__pyx_5 >= PyList_GET_SIZE(__pyx_3)) break;
        __pyx_6 = PyList_GET_ITEM(__pyx_3, __pyx_5); Py_INCREF(__pyx_6); __pyx_5++;
      } else if (likely(PyTuple_CheckExact(__pyx_3))) {
        if (__pyx_5 >= PyTuple_GET_SIZE(__pyx_3)) break;
        __pyx_6 = PyTuple_GET_ITEM(__pyx_3, __pyx_5); Py_INCREF(__pyx_6); __pyx_5++;
      } else {
        __pyx_6 = PyIter_Next(__pyx_3);
        if (!__pyx_6) {
          if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
          break;
        }
      }
      if (PyTuple_CheckExact(__pyx_6) && PyTuple_GET_SIZE(__pyx_6) == 2) {
        PyObject* tuple = __pyx_6;
        __pyx_9 = PyTuple_GET_ITEM(tuple, 0);
        Py_INCREF(__pyx_9);
        Py_DECREF(__pyx_v_key);
        __pyx_v_key = __pyx_9;
        __pyx_9 = 0;
        __pyx_9 = PyTuple_GET_ITEM(tuple, 1);
        Py_INCREF(__pyx_9);
        __pyx_8 = __pyx_PyInt_int(__pyx_9); if (unlikely((__pyx_8 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_DECREF(__pyx_9); __pyx_9 = 0;
        __pyx_v_id = __pyx_8;
        Py_DECREF(__pyx_6); __pyx_6 = 0;
      }
      else {
        __pyx_1 = PyObject_GetIter(__pyx_6); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_DECREF(__pyx_6); __pyx_6 = 0;
        __pyx_9 = __Pyx_UnpackItem(__pyx_1, 0); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_DECREF(__pyx_v_key);
        __pyx_v_key = __pyx_9;
        __pyx_9 = 0;
        __pyx_9 = __Pyx_UnpackItem(__pyx_1, 1); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        __pyx_8 = __pyx_PyInt_int(__pyx_9); if (unlikely((__pyx_8 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_DECREF(__pyx_9); __pyx_9 = 0;
        __pyx_v_id = __pyx_8;
        if (__Pyx_EndUnpack(__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        Py_DECREF(__pyx_1); __pyx_1 = 0;
      }

      /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":116
 *     if remlist:
 *         for key, id in remlist:
 *             PyDict_DelItem(inverted_store, key)             # <<<<<<<<<<<<<<
 *             PyDict_DelItem(store, id)
 * 
 */
      PyDict_DelItem(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store), __pyx_v_key);

      /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":117
 *         for key, id in remlist:
 *             PyDict_DelItem(inverted_store, key)
 *             PyDict_DelItem(store, id)             # <<<<<<<<<<<<<<
 * 
 * def prune_stores():
 */
      __pyx_9 = PyInt_FromLong(__pyx_v_id); if (unlikely(!__pyx_9)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      PyDict_DelItem(((PyObject *)__pyx_v_9protoplex_9_speedups_store), __pyx_9);
      Py_DECREF(__pyx_9); __pyx_9 = 0;
    }
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L10;
  }
  __pyx_L10:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_9);
  __Pyx_AddTraceback("protoplex._speedups._prune_stores");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_remlist);
  Py_DECREF(__pyx_v_surv);
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_val);
  Py_DECREF(__pyx_v_item);
  return __pyx_r;
}

/* "/Users/tav/work/trunk/protoplex/_speedups.pyx":119
 *             PyDict_DelItem(store, id)
 * 
 * def prune_stores():             # <<<<<<<<<<<<<<
 *     _prune_stores()
 * 
 */

static PyObject *__pyx_pf_9protoplex_9_speedups_prune_stores(PyObject *__pyx_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_9protoplex_9_speedups_prune_stores(PyObject *__pyx_self, PyObject *unused) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_self = __pyx_self;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":120
 * 
 * def prune_stores():
 *     _prune_stores()             # <<<<<<<<<<<<<<
 * 
 * def get_stores():
 */
  __pyx_1 = __pyx_f_9protoplex_9_speedups__prune_stores(); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("protoplex._speedups.prune_stores");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/Users/tav/work/trunk/protoplex/_speedups.pyx":122
 *     _prune_stores()
 * 
 * def get_stores():             # <<<<<<<<<<<<<<
 *     return (store, inverted_store)
 * 
 */

static PyObject *__pyx_pf_9protoplex_9_speedups_get_stores(PyObject *__pyx_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_9protoplex_9_speedups_get_stores(PyObject *__pyx_self, PyObject *unused) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  __pyx_self = __pyx_self;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":123
 * 
 * def get_stores():
 *     return (store, inverted_store)             # <<<<<<<<<<<<<<
 * 
 * # http://docs.python.org/c-api/
 */
  __pyx_1 = PyTuple_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(((PyObject *)__pyx_v_9protoplex_9_speedups_store));
  PyTuple_SET_ITEM(__pyx_1, 0, ((PyObject *)__pyx_v_9protoplex_9_speedups_store));
  Py_INCREF(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store));
  PyTuple_SET_ITEM(__pyx_1, 1, ((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store));
  __pyx_r = ((PyObject *)__pyx_1);
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("protoplex._speedups.get_stores");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_tp_new_9protoplex_9_speedups_Namespace(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_9protoplex_9_speedups_Namespace *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_9protoplex_9_speedups_Namespace *)o);
  p->__weakref__ = 0;
  p->env = ((PyObject *)Py_None); Py_INCREF(Py_None);
  if (__pyx_pf_9protoplex_9_speedups_9Namespace___cinit__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_9protoplex_9_speedups_Namespace(PyObject *o) {
  struct __pyx_obj_9protoplex_9_speedups_Namespace *p = (struct __pyx_obj_9protoplex_9_speedups_Namespace *)o;
  if (p->__weakref__) PyObject_ClearWeakRefs(o);
  Py_XDECREF(((PyObject *)p->env));
  (*Py_TYPE(o)->tp_free)(o);
}

static int __pyx_tp_traverse_9protoplex_9_speedups_Namespace(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_9protoplex_9_speedups_Namespace *p = (struct __pyx_obj_9protoplex_9_speedups_Namespace *)o;
  if (p->env) {
    e = (*v)(p->env, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_9protoplex_9_speedups_Namespace(PyObject *o) {
  struct __pyx_obj_9protoplex_9_speedups_Namespace *p = (struct __pyx_obj_9protoplex_9_speedups_Namespace *)o;
  PyObject* tmp;
  tmp = ((PyObject*)p->env);
  p->env = ((PyObject *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(tmp);
  return 0;
}

static PyObject *__pyx_tp_getattro_9protoplex_9_speedups_Namespace(PyObject *o, PyObject *n) {
  PyObject *v = __pyx_pf_9protoplex_9_speedups_9Namespace___getattribute__(o, n);
  return v;
}

static struct PyMethodDef __pyx_methods_9protoplex_9_speedups_Namespace[] = {
  {"__getattribute__", (PyCFunction)__pyx_pf_9protoplex_9_speedups_9Namespace___getattribute__, METH_O, 0},
  {"__str__", (PyCFunction)__pyx_pf_9protoplex_9_speedups_9Namespace___str__, METH_NOARGS|METH_COEXIST, 0},
  {"__repr__", (PyCFunction)__pyx_pf_9protoplex_9_speedups_9Namespace___repr__, METH_NOARGS|METH_COEXIST, 0},
  {"__dir__", (PyCFunction)__pyx_pf_9protoplex_9_speedups_9Namespace___dir__, METH_NOARGS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Namespace = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_divide*/
  #endif
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_coerce*/
  #endif
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_oct*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*nb_hex*/
  #endif
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_inplace_divide*/
  #endif
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if (PY_MAJOR_VERSION >= 3) || (Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX)
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Namespace = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Namespace = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Namespace = {
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getreadbuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getwritebuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getsegcount*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getcharbuffer*/
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  0, /*bf_getbuffer*/
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  0, /*bf_releasebuffer*/
  #endif
};

PyTypeObject __pyx_type_9protoplex_9_speedups_Namespace = {
  PyVarObject_HEAD_INIT(0, 0)
  "protoplex._speedups.Namespace", /*tp_name*/
  sizeof(struct __pyx_obj_9protoplex_9_speedups_Namespace), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9protoplex_9_speedups_Namespace, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_pf_9protoplex_9_speedups_9Namespace___repr__, /*tp_repr*/
  &__pyx_tp_as_number_Namespace, /*tp_as_number*/
  &__pyx_tp_as_sequence_Namespace, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Namespace, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  __pyx_pf_9protoplex_9_speedups_9Namespace___str__, /*tp_str*/
  __pyx_tp_getattro_9protoplex_9_speedups_Namespace, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Namespace, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_NEWBUFFER|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "A Namespace object.", /*tp_doc*/
  __pyx_tp_traverse_9protoplex_9_speedups_Namespace, /*tp_traverse*/
  __pyx_tp_clear_9protoplex_9_speedups_Namespace, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9protoplex_9_speedups_Namespace, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9protoplex_9_speedups_Namespace, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"prune_stores", (PyCFunction)__pyx_pf_9protoplex_9_speedups_prune_stores, METH_NOARGS, 0},
  {"get_stores", (PyCFunction)__pyx_pf_9protoplex_9_speedups_get_stores, METH_NOARGS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    "_speedups",
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp___cinit__, __pyx_k___cinit__, sizeof(__pyx_k___cinit__), 1, 1, 1},
  {&__pyx_kp___getattribute__, __pyx_k___getattribute__, sizeof(__pyx_k___getattribute__), 1, 1, 1},
  {&__pyx_kp___str__, __pyx_k___str__, sizeof(__pyx_k___str__), 1, 1, 1},
  {&__pyx_kp___repr__, __pyx_k___repr__, sizeof(__pyx_k___repr__), 1, 1, 1},
  {&__pyx_kp___dir__, __pyx_k___dir__, sizeof(__pyx_k___dir__), 1, 1, 1},
  {&__pyx_kp_attribute, __pyx_k_attribute, sizeof(__pyx_k_attribute), 1, 1, 1},
  {&__pyx_kp_sys, __pyx_k_sys, sizeof(__pyx_k_sys), 1, 1, 1},
  {&__pyx_kp__getframe, __pyx_k__getframe, sizeof(__pyx_k__getframe), 1, 1, 1},
  {&__pyx_kp_get_frame, __pyx_k_get_frame, sizeof(__pyx_k_get_frame), 0, 1, 1},
  {&__pyx_kp_f_locals, __pyx_k_f_locals, sizeof(__pyx_k_f_locals), 1, 1, 1},
  {&__pyx_kp_startswith, __pyx_k_startswith, sizeof(__pyx_k_startswith), 1, 1, 1},
  {&__pyx_kp_1, __pyx_k_1, sizeof(__pyx_k_1), 0, 1, 0},
  {&__pyx_kp_2, __pyx_k_2, sizeof(__pyx_k_2), 0, 1, 0},
  {&__pyx_kp_AttributeError, __pyx_k_AttributeError, sizeof(__pyx_k_AttributeError), 1, 1, 1},
  {&__pyx_kp_4, __pyx_k_4, sizeof(__pyx_k_4), 0, 1, 0},
  {&__pyx_kp_5, __pyx_k_5, sizeof(__pyx_k_5), 0, 1, 0},
  {&__pyx_kp_3, __pyx_k_3, sizeof(__pyx_k_3), 0, 0, 0},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  __pyx_builtin_AttributeError = __Pyx_GetName(__pyx_b, __pyx_kp_AttributeError); if (!__pyx_builtin_AttributeError) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  return 0;
  __pyx_L1_error:;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  __pyx_int_0 = PyInt_FromLong(0); if (unlikely(!__pyx_int_0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_speedups(void); /*proto*/
PyMODINIT_FUNC init_speedups(void)
#else
PyMODINIT_FUNC PyInit__speedups(void); /*proto*/
PyMODINIT_FUNC PyInit__speedups(void)
#endif
{
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Library function declarations ---*/
  __pyx_init_filenames();
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4("_speedups", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  __pyx_v_9protoplex_9_speedups_store = ((PyObject *)Py_None); Py_INCREF(Py_None);
  __pyx_v_9protoplex_9_speedups_inverted_store = ((PyObject *)Py_None); Py_INCREF(Py_None);
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  if (PyType_Ready(&__pyx_type_9protoplex_9_speedups_Namespace) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttrString(__pyx_m, "Namespace", (PyObject *)&__pyx_type_9protoplex_9_speedups_Namespace) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__pyx_type_9protoplex_9_speedups_Namespace.tp_weaklistoffset == 0) __pyx_type_9protoplex_9_speedups_Namespace.tp_weaklistoffset = offsetof(struct __pyx_obj_9protoplex_9_speedups_Namespace, __weakref__);
  __pyx_ptype_9protoplex_9_speedups_Namespace = &__pyx_type_9protoplex_9_speedups_Namespace;
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":1
 * from sys import _getframe as get_frame             # <<<<<<<<<<<<<<
 * 
 * cdef extern from "Python.h":
 */
  __pyx_1 = PyList_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_kp__getframe);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_kp__getframe);
  __pyx_2 = __Pyx_Import(__pyx_kp_sys, ((PyObject *)__pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_kp__getframe); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_get_frame, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":30
 * cdef int last_id
 * 
 * store = {}             # <<<<<<<<<<<<<<
 * inverted_store = {}
 * last_id = 1 # long
 */
  __pyx_2 = PyDict_New(); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_v_9protoplex_9_speedups_store));
  __pyx_v_9protoplex_9_speedups_store = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":31
 * 
 * store = {}
 * inverted_store = {}             # <<<<<<<<<<<<<<
 * last_id = 1 # long
 * 
 */
  __pyx_1 = PyDict_New(); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_v_9protoplex_9_speedups_inverted_store));
  __pyx_v_9protoplex_9_speedups_inverted_store = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":32
 * store = {}
 * inverted_store = {}
 * last_id = 1 # long             # <<<<<<<<<<<<<<
 * 
 * cdef class Namespace:
 */
  __pyx_v_9protoplex_9_speedups_last_id = 1;

  /* "/Users/tav/work/trunk/protoplex/_speedups.pyx":122
 *     _prune_stores()
 * 
 * def get_stores():             # <<<<<<<<<<<<<<
 *     return (store, inverted_store)
 * 
 */
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("protoplex._speedups");
  #if PY_MAJOR_VERSION >= 3
  return NULL;
  #endif
}

static const char *__pyx_filenames[] = {
  "_speedups.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_RaiseArgtupleInvalid(
    const char* func_name,
    int exact,
    Py_ssize_t num_min,
    Py_ssize_t num_max,
    Py_ssize_t num_found)
{
    Py_ssize_t num_expected;
    const char *number, *more_or_less;

    if (num_found < num_min) {
        num_expected = num_min;
        more_or_less = "at least";
    } else {
        num_expected = num_max;
        more_or_less = "at most";
    }
    if (exact) {
        more_or_less = "exactly";
    }
    number = (num_expected == 1) ? "" : "s";
    PyErr_Format(PyExc_TypeError,
        #if PY_VERSION_HEX < 0x02050000
            "%s() takes %s %d positional argument%s (%d given)",
        #else
            "%s() takes %s %zd positional argument%s (%zd given)",
        #endif
        func_name, more_or_less, num_expected, number, num_found);
}

static INLINE int __Pyx_CheckKeywordStrings(
    PyObject *kwdict,
    const char* function_name,
    int kw_allowed)
{
    PyObject* key = 0;
    Py_ssize_t pos = 0;
    while (PyDict_Next(kwdict, &pos, &key, 0)) {
        #if PY_MAJOR_VERSION < 3
        if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key)))
        #else
        if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key)))
        #endif
            goto invalid_keyword_type;
    }
    if ((!kw_allowed) && unlikely(key))
        goto invalid_keyword;
    return 1;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    return 0;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
    return 0;
}



static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                type = 0;
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) Py_TYPE(type);
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    __Pyx_ErrRestore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb) {
    PyObject *tmp_type, *tmp_value, *tmp_tb;
    PyThreadState *tstate = PyThreadState_GET();

    tmp_type = tstate->curexc_type;
    tmp_value = tstate->curexc_value;
    tmp_tb = tstate->curexc_traceback;
    tstate->curexc_type = type;
    tstate->curexc_value = value;
    tstate->curexc_traceback = tb;
    Py_XDECREF(tmp_type);
    Py_XDECREF(tmp_value);
    Py_XDECREF(tmp_tb);
}

static INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb) {
    PyThreadState *tstate = PyThreadState_GET();
    *type = tstate->curexc_type;
    *value = tstate->curexc_value;
    *tb = tstate->curexc_traceback;

    tstate->curexc_type = 0;
    tstate->curexc_value = 0;
    tstate->curexc_traceback = 0;
}


static PyObject *__Pyx_UnpackItem(PyObject *iter, Py_ssize_t index) {
    PyObject *item;
    if (!(item = PyIter_Next(iter))) {
        if (!PyErr_Occurred()) {
            PyErr_Format(PyExc_ValueError,
                #if PY_VERSION_HEX < 0x02050000
                    "need more than %d values to unpack", (int)index);
                #else
                    "need more than %zd values to unpack", index);
                #endif
        }
    }
    return item;
}

static int __Pyx_EndUnpack(PyObject *iter) {
    PyObject *item;
    if ((item = PyIter_Next(iter))) {
        Py_DECREF(item);
        PyErr_SetString(PyExc_ValueError, "too many values to unpack");
        return -1;
    }
    else if (!PyErr_Occurred())
        return 0;
    else
        return -1;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

