#! /usr/bin/env python2.6

# Released into the Public Domain. See documentation/legal.txt for more info.
# Author: tav <tav@espians.com>

import plexnetenv

from plexnet.tool.docspec import runner

runner()
