#! /bin/sh

# Released into the Public Domain. See documentation/legal.txt for more info.
# Author: tav <tav@espians.com>

UNAME=$(uname -s)
LSOF=$(lsof -p $$ 2> /dev/null | grep -E "/"$(basename $0)"$")

if [ "$UNAME" == "Linux" ]; then
    SCRIPT_PATH=$(echo $LSOF | sed -r s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
fi

if [ "$UNAME" == "Darwin" ]; then
    SCRIPT_PATH=$(echo $LSOF | sed -E s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
fi

STARTUP_DIRECTORY=$(dirname $SCRIPT_PATH)
PLEXNET_ROOT=$(dirname $(dirname $(dirname $SCRIPT_PATH)))

if [ ! "$PLEXNET_LOCAL" ]; then
    source $STARTUP_DIRECTORY/plexnetenv.sh noinstall
fi

# first run redpill.py with the system python to install our custom one if needed

if [ ! -f $PLEXNET_LOCAL/bin/python ]; then
	python $STARTUP_DIRECTORY/redpill.py $@
fi

$PLEXNET_LOCAL/bin/python $STARTUP_DIRECTORY/redpill.py $@
